### ISSUE TITLE
error unable to load scene main

### ISSUE THREAD

**Issue by MathieuPayment** [VR-Tracker/Unity-Plugin#5]
Error message in unity consol when load the main game scene. 
Probably caused by not having the pairing prefabg in the game scene.
The pairing prefabg cannot be added in unity version lower than 2018.2. There is a compatibility bug with prefab build on version 2018.2 and higher

**Comment by JulesThuillier** [comment]
Please copy the log here when this happens

**Comment by JulesThuillier** [comment]
Pairing prefab rolled back to 2018.1
